apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  ports:
  - port: 80 
    name: http
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
