project: default
source:
  repoURL: 'https://github.com/joon9293/helm-demo.git'
  path: ./
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: test
syncPolicy:
  automated: {}
