apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: service-monitor-spring-demo
  name: service-monitor-spring-demo
  namespace: test
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
